const voices = [
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (wuu-CN, XiaotongNeural)",
        "DisplayName": "Xiaotong",
        "LocalName": "晓彤",
        "ShortName": "wuu-CN-XiaotongNeural",
        "Gender": "Female",
        "Locale": "wuu-CN",
        "LocaleName": "Chinese (Wu, Simplified)",
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "WordsPerMinute": "238"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (wuu-CN, YunzheNeural)",
        "DisplayName": "Yunzhe",
        "LocalName": "云哲",
        "ShortName": "wuu-CN-YunzheNeural",
        "Gender": "Male",
        "Locale": "wuu-CN",
        "LocaleName": "Chinese (Wu, Simplified)",
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "WordsPerMinute": "244"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (yue-CN, XiaoMinNeural)",
        "DisplayName": "XiaoMin",
        "LocalName": "晓敏",
        "ShortName": "yue-CN-XiaoMinNeural",
        "Gender": "Female",
        "Locale": "yue-CN",
        "LocaleName": "Chinese (Cantonese, Simplified)",
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "WordsPerMinute": "214"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (yue-CN, YunSongNeural)",
        "DisplayName": "YunSong",
        "LocalName": "云松",
        "ShortName": "yue-CN-YunSongNeural",
        "Gender": "Male",
        "Locale": "yue-CN",
        "LocaleName": "Chinese (Cantonese, Simplified)",
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "WordsPerMinute": "221"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN, XiaoxiaoNeural)",
        "DisplayName": "Xiaoxiao",
        "LocalName": "晓晓",
        "ShortName": "zh-CN-XiaoxiaoNeural",
        "Gender": "Female",
        "Locale": "zh-CN",
        "LocaleName": "Chinese (Mandarin, Simplified)",
        "StyleList": [
            "assistant",
            "chat",
            "customerservice",
            "newscast",
            "affectionate",
            "angry",
            "calm",
            "cheerful",
            "disgruntled",
            "fearful",
            "gentle",
            "lyrical",
            "sad",
            "serious",
            "poetry-reading",
            "friendly",
            "chat-casual",
            "whisper",
            "sorry"
        ],
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "WordsPerMinute": "274"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN, YunxiNeural)",
        "DisplayName": "Yunxi",
        "LocalName": "云希",
        "ShortName": "zh-CN-YunxiNeural",
        "Gender": "Male",
        "Locale": "zh-CN",
        "LocaleName": "Chinese (Mandarin, Simplified)",
        "StyleList": [
            "narration-relaxed",
            "embarrassed",
            "fearful",
            "cheerful",
            "disgruntled",
            "serious",
            "angry",
            "sad",
            "depressed",
            "chat",
            "assistant",
            "newscast"
        ],
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "RolePlayList": [
            "Narrator",
            "YoungAdultMale",
            "Boy"
        ],
        "WordsPerMinute": "293"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN, YunjianNeural)",
        "DisplayName": "Yunjian",
        "LocalName": "云健",
        "ShortName": "zh-CN-YunjianNeural",
        "Gender": "Male",
        "Locale": "zh-CN",
        "LocaleName": "Chinese (Mandarin, Simplified)",
        "StyleList": [
            "narration-relaxed",
            "sports-commentary",
            "sports-commentary-excited",
            "angry",
            "disgruntled",
            "cheerful",
            "sad",
            "serious",
            "depressed",
            "documentary-narration"
        ],
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "WordsPerMinute": "279"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN, XiaoyiNeural)",
        "DisplayName": "Xiaoyi",
        "LocalName": "晓伊",
        "ShortName": "zh-CN-XiaoyiNeural",
        "Gender": "Female",
        "Locale": "zh-CN",
        "LocaleName": "Chinese (Mandarin, Simplified)",
        "StyleList": [
            "angry",
            "disgruntled",
            "affectionate",
            "cheerful",
            "fearful",
            "sad",
            "embarrassed",
            "serious",
            "gentle"
        ],
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "WordsPerMinute": "263"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN, YunyangNeural)",
        "DisplayName": "Yunyang",
        "LocalName": "云扬",
        "ShortName": "zh-CN-YunyangNeural",
        "Gender": "Male",
        "Locale": "zh-CN",
        "LocaleName": "Chinese (Mandarin, Simplified)",
        "StyleList": [
            "customerservice",
            "narration-professional",
            "newscast-casual"
        ],
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "WordsPerMinute": "293"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN, XiaochenNeural)",
        "DisplayName": "Xiaochen",
        "LocalName": "晓辰",
        "ShortName": "zh-CN-XiaochenNeural",
        "Gender": "Female",
        "Locale": "zh-CN",
        "LocaleName": "Chinese (Mandarin, Simplified)",
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "WordsPerMinute": "283"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN, XiaohanNeural)",
        "DisplayName": "Xiaohan",
        "LocalName": "晓涵",
        "ShortName": "zh-CN-XiaohanNeural",
        "Gender": "Female",
        "Locale": "zh-CN",
        "LocaleName": "Chinese (Mandarin, Simplified)",
        "StyleList": [
            "calm",
            "fearful",
            "cheerful",
            "disgruntled",
            "serious",
            "angry",
            "sad",
            "gentle",
            "affectionate",
            "embarrassed"
        ],
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "WordsPerMinute": "259"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN, XiaomengNeural)",
        "DisplayName": "Xiaomeng",
        "LocalName": "晓梦",
        "ShortName": "zh-CN-XiaomengNeural",
        "Gender": "Female",
        "Locale": "zh-CN",
        "LocaleName": "Chinese (Mandarin, Simplified)",
        "StyleList": [
            "chat"
        ],
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "WordsPerMinute": "272"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN, XiaomoNeural)",
        "DisplayName": "Xiaomo",
        "LocalName": "晓墨",
        "ShortName": "zh-CN-XiaomoNeural",
        "Gender": "Female",
        "Locale": "zh-CN",
        "LocaleName": "Chinese (Mandarin, Simplified)",
        "StyleList": [
            "embarrassed",
            "calm",
            "fearful",
            "cheerful",
            "disgruntled",
            "serious",
            "angry",
            "sad",
            "depressed",
            "affectionate",
            "gentle",
            "envious"
        ],
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "RolePlayList": [
            "YoungAdultFemale",
            "YoungAdultMale",
            "OlderAdultFemale",
            "OlderAdultMale",
            "SeniorFemale",
            "SeniorMale",
            "Girl",
            "Boy"
        ],
        "WordsPerMinute": "286"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN, XiaoqiuNeural)",
        "DisplayName": "Xiaoqiu",
        "LocalName": "晓秋",
        "ShortName": "zh-CN-XiaoqiuNeural",
        "Gender": "Female",
        "Locale": "zh-CN",
        "LocaleName": "Chinese (Mandarin, Simplified)",
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "WordsPerMinute": "232"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN, XiaoruiNeural)",
        "DisplayName": "Xiaorui",
        "LocalName": "晓睿",
        "ShortName": "zh-CN-XiaoruiNeural",
        "Gender": "Female",
        "Locale": "zh-CN",
        "LocaleName": "Chinese (Mandarin, Simplified)",
        "StyleList": [
            "calm",
            "fearful",
            "angry",
            "sad"
        ],
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "WordsPerMinute": "243"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN, XiaoshuangNeural)",
        "DisplayName": "Xiaoshuang",
        "LocalName": "晓双",
        "ShortName": "zh-CN-XiaoshuangNeural",
        "Gender": "Female",
        "Locale": "zh-CN",
        "LocaleName": "Chinese (Mandarin, Simplified)",
        "StyleList": [
            "chat"
        ],
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "WordsPerMinute": "225"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN, XiaoyanNeural)",
        "DisplayName": "Xiaoyan",
        "LocalName": "晓颜",
        "ShortName": "zh-CN-XiaoyanNeural",
        "Gender": "Female",
        "Locale": "zh-CN",
        "LocaleName": "Chinese (Mandarin, Simplified)",
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "WordsPerMinute": "279"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN, XiaoyouNeural)",
        "DisplayName": "Xiaoyou",
        "LocalName": "晓悠",
        "ShortName": "zh-CN-XiaoyouNeural",
        "Gender": "Female",
        "Locale": "zh-CN",
        "LocaleName": "Chinese (Mandarin, Simplified)",
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "WordsPerMinute": "211"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN, XiaozhenNeural)",
        "DisplayName": "Xiaozhen",
        "LocalName": "晓甄",
        "ShortName": "zh-CN-XiaozhenNeural",
        "Gender": "Female",
        "Locale": "zh-CN",
        "LocaleName": "Chinese (Mandarin, Simplified)",
        "StyleList": [
            "angry",
            "disgruntled",
            "cheerful",
            "fearful",
            "sad",
            "serious"
        ],
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "WordsPerMinute": "273"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN, YunfengNeural)",
        "DisplayName": "Yunfeng",
        "LocalName": "云枫",
        "ShortName": "zh-CN-YunfengNeural",
        "Gender": "Male",
        "Locale": "zh-CN",
        "LocaleName": "Chinese (Mandarin, Simplified)",
        "StyleList": [
            "angry",
            "disgruntled",
            "cheerful",
            "fearful",
            "sad",
            "serious",
            "depressed"
        ],
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "WordsPerMinute": "320"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN, YunhaoNeural)",
        "DisplayName": "Yunhao",
        "LocalName": "云皓",
        "ShortName": "zh-CN-YunhaoNeural",
        "Gender": "Male",
        "Locale": "zh-CN",
        "LocaleName": "Chinese (Mandarin, Simplified)",
        "StyleList": [
            "advertisement-upbeat"
        ],
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "WordsPerMinute": "315"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN, YunxiaNeural)",
        "DisplayName": "Yunxia",
        "LocalName": "云夏",
        "ShortName": "zh-CN-YunxiaNeural",
        "Gender": "Male",
        "Locale": "zh-CN",
        "LocaleName": "Chinese (Mandarin, Simplified)",
        "StyleList": [
            "calm",
            "fearful",
            "cheerful",
            "angry",
            "sad"
        ],
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "WordsPerMinute": "269"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN, YunyeNeural)",
        "DisplayName": "Yunye",
        "LocalName": "云野",
        "ShortName": "zh-CN-YunyeNeural",
        "Gender": "Male",
        "Locale": "zh-CN",
        "LocaleName": "Chinese (Mandarin, Simplified)",
        "StyleList": [
            "embarrassed",
            "calm",
            "fearful",
            "cheerful",
            "disgruntled",
            "serious",
            "angry",
            "sad"
        ],
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "RolePlayList": [
            "YoungAdultFemale",
            "YoungAdultMale",
            "OlderAdultFemale",
            "OlderAdultMale",
            "SeniorFemale",
            "SeniorMale",
            "Girl",
            "Boy"
        ],
        "WordsPerMinute": "278"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN, YunzeNeural)",
        "DisplayName": "Yunze",
        "LocalName": "云泽",
        "ShortName": "zh-CN-YunzeNeural",
        "Gender": "Male",
        "Locale": "zh-CN",
        "LocaleName": "Chinese (Mandarin, Simplified)",
        "StyleList": [
            "calm",
            "fearful",
            "cheerful",
            "disgruntled",
            "serious",
            "angry",
            "sad",
            "depressed",
            "documentary-narration"
        ],
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "RolePlayList": [
            "OlderAdultMale",
            "SeniorMale"
        ],
        "WordsPerMinute": "255"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN, XiaochenMultilingualNeural)",
        "DisplayName": "Xiaochen Multilingual",
        "LocalName": "Xiaochen Multilingual",
        "ShortName": "zh-CN-XiaochenMultilingualNeural",
        "Gender": "Female",
        "Locale": "zh-CN",
        "LocaleName": "Chinese (Mandarin, Simplified)",
        "SecondaryLocaleList": [
            "af-ZA",
            "am-ET",
            "ar-EG",
            "ar-SA",
            "az-AZ",
            "bg-BG",
            "bn-BD",
            "bn-IN",
            "bs-BA",
            "ca-ES",
            "cs-CZ",
            "cy-GB",
            "da-DK",
            "de-AT",
            "de-CH",
            "de-DE",
            "el-GR",
            "en-AU",
            "en-CA",
            "en-GB",
            "en-IE",
            "en-IN",
            "en-US",
            "es-ES",
            "es-MX",
            "et-EE",
            "eu-ES",
            "fa-IR",
            "fi-FI",
            "fil-PH",
            "fr-BE",
            "fr-CA",
            "fr-CH",
            "fr-FR",
            "ga-IE",
            "gl-ES",
            "he-IL",
            "hi-IN",
            "hr-HR",
            "hu-HU",
            "hy-AM",
            "id-ID",
            "is-IS",
            "it-IT",
            "ja-JP",
            "jv-ID",
            "ka-GE",
            "kk-KZ",
            "km-KH",
            "kn-IN",
            "ko-KR",
            "lo-LA",
            "lt-LT",
            "lv-LV",
            "mk-MK",
            "ml-IN",
            "mn-MN",
            "ms-MY",
            "mt-MT",
            "my-MM",
            "nb-NO",
            "ne-NP",
            "nl-BE",
            "nl-NL",
            "pl-PL",
            "ps-AF",
            "pt-BR",
            "pt-PT",
            "ro-RO",
            "ru-RU",
            "si-LK",
            "sk-SK",
            "sl-SI",
            "so-SO",
            "sq-AL",
            "sr-RS",
            "su-ID",
            "sv-SE",
            "sw-KE",
            "ta-IN",
            "te-IN",
            "th-TH",
            "tr-TR",
            "uk-UA",
            "ur-PK",
            "uz-UZ",
            "vi-VN",
            "zh-CN",
            "zh-HK",
            "zh-TW",
            "zu-ZA"
        ],
        "SampleRateHertz": "24000",
        "VoiceType": "Neural",
        "Status": "Preview",
        "WordsPerMinute": "190"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN, XiaorouNeural)",
        "DisplayName": "Xiaorou",
        "LocalName": "晓柔",
        "ShortName": "zh-CN-XiaorouNeural",
        "Gender": "Female",
        "Locale": "zh-CN",
        "LocaleName": "Chinese (Mandarin, Simplified)",
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "Preview"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN, XiaoxiaoDialectsNeural)",
        "DisplayName": "XiaoxiaoDialects",
        "LocalName": "晓晓方言",
        "ShortName": "zh-CN-XiaoxiaoDialectsNeural",
        "Gender": "Female",
        "Locale": "zh-CN",
        "LocaleName": "Chinese (Mandarin, Simplified)",
        "SecondaryLocaleList": [
            "zh-CN-shaanxi",
            "zh-CN-sichuan",
            "zh-CN-shanxi",
            "zh-CN-anhui",
            "zh-CN-hunan",
            "zh-CN-gansu",
            "zh-CN-shandong",
            "zh-CN-henan",
            "zh-CN-liaoning",
            "zh-TW",
            "nan-CN"
        ],
        "SampleRateHertz": "24000",
        "VoiceType": "Neural",
        "Status": "Preview"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN, XiaoxiaoMultilingualNeural)",
        "DisplayName": "Xiaoxiao Multilingual",
        "LocalName": "Xiaoxiao Multilingual",
        "ShortName": "zh-CN-XiaoxiaoMultilingualNeural",
        "Gender": "Female",
        "Locale": "zh-CN",
        "LocaleName": "Chinese (Mandarin, Simplified)",
        "SecondaryLocaleList": [
            "af-ZA",
            "am-ET",
            "ar-EG",
            "ar-SA",
            "az-AZ",
            "bg-BG",
            "bn-BD",
            "bn-IN",
            "bs-BA",
            "ca-ES",
            "cs-CZ",
            "cy-GB",
            "da-DK",
            "de-AT",
            "de-CH",
            "de-DE",
            "el-GR",
            "en-AU",
            "en-CA",
            "en-GB",
            "en-IE",
            "en-IN",
            "en-US",
            "es-ES",
            "es-MX",
            "et-EE",
            "eu-ES",
            "fa-IR",
            "fi-FI",
            "fil-PH",
            "fr-BE",
            "fr-CA",
            "fr-CH",
            "fr-FR",
            "ga-IE",
            "gl-ES",
            "he-IL",
            "hi-IN",
            "hr-HR",
            "hu-HU",
            "hy-AM",
            "id-ID",
            "is-IS",
            "it-IT",
            "ja-JP",
            "jv-ID",
            "ka-GE",
            "kk-KZ",
            "km-KH",
            "kn-IN",
            "ko-KR",
            "lo-LA",
            "lt-LT",
            "lv-LV",
            "mk-MK",
            "ml-IN",
            "mn-MN",
            "ms-MY",
            "mt-MT",
            "my-MM",
            "nb-NO",
            "ne-NP",
            "nl-BE",
            "nl-NL",
            "pl-PL",
            "ps-AF",
            "pt-BR",
            "pt-PT",
            "ro-RO",
            "ru-RU",
            "si-LK",
            "sk-SK",
            "sl-SI",
            "so-SO",
            "sq-AL",
            "sr-RS",
            "su-ID",
            "sv-SE",
            "sw-KE",
            "ta-IN",
            "te-IN",
            "th-TH",
            "tr-TR",
            "uk-UA",
            "ur-PK",
            "uz-UZ",
            "vi-VN",
            "zh-CN",
            "zh-HK",
            "zh-TW",
            "zu-ZA"
        ],
        "SampleRateHertz": "24000",
        "VoiceType": "Neural",
        "Status": "Preview",
        "WordsPerMinute": "190"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN, XiaoyuMultilingualNeural)",
        "DisplayName": "Xiaoyu Multilingual",
        "LocalName": "Xiaoyu Multilingual",
        "ShortName": "zh-CN-XiaoyuMultilingualNeural",
        "Gender": "Female",
        "Locale": "zh-CN",
        "LocaleName": "Chinese (Mandarin, Simplified)",
        "SecondaryLocaleList": [
            "af-ZA",
            "am-ET",
            "ar-EG",
            "ar-SA",
            "az-AZ",
            "bg-BG",
            "bn-BD",
            "bn-IN",
            "bs-BA",
            "ca-ES",
            "cs-CZ",
            "cy-GB",
            "da-DK",
            "de-AT",
            "de-CH",
            "de-DE",
            "el-GR",
            "en-AU",
            "en-CA",
            "en-GB",
            "en-IE",
            "en-IN",
            "en-US",
            "es-ES",
            "es-MX",
            "et-EE",
            "eu-ES",
            "fa-IR",
            "fi-FI",
            "fil-PH",
            "fr-BE",
            "fr-CA",
            "fr-CH",
            "fr-FR",
            "ga-IE",
            "gl-ES",
            "he-IL",
            "hi-IN",
            "hr-HR",
            "hu-HU",
            "hy-AM",
            "id-ID",
            "is-IS",
            "it-IT",
            "ja-JP",
            "jv-ID",
            "ka-GE",
            "kk-KZ",
            "km-KH",
            "kn-IN",
            "ko-KR",
            "lo-LA",
            "lt-LT",
            "lv-LV",
            "mk-MK",
            "ml-IN",
            "mn-MN",
            "ms-MY",
            "mt-MT",
            "my-MM",
            "nb-NO",
            "ne-NP",
            "nl-BE",
            "nl-NL",
            "pl-PL",
            "ps-AF",
            "pt-BR",
            "pt-PT",
            "ro-RO",
            "ru-RU",
            "si-LK",
            "sk-SK",
            "sl-SI",
            "so-SO",
            "sq-AL",
            "sr-RS",
            "su-ID",
            "sv-SE",
            "sw-KE",
            "ta-IN",
            "te-IN",
            "th-TH",
            "tr-TR",
            "uk-UA",
            "ur-PK",
            "uz-UZ",
            "vi-VN",
            "zh-CN",
            "zh-HK",
            "zh-TW",
            "zu-ZA"
        ],
        "SampleRateHertz": "24000",
        "VoiceType": "Neural",
        "Status": "Preview",
        "WordsPerMinute": "190"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN, YunjieNeural)",
        "DisplayName": "Yunjie",
        "LocalName": "云杰",
        "ShortName": "zh-CN-YunjieNeural",
        "Gender": "Male",
        "Locale": "zh-CN",
        "LocaleName": "Chinese (Mandarin, Simplified)",
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "Preview"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN, YunyiMultilingualNeural)",
        "DisplayName": "Yunyi Multilingual",
        "LocalName": "Yunyi Multilingual",
        "ShortName": "zh-CN-YunyiMultilingualNeural",
        "Gender": "Male",
        "Locale": "zh-CN",
        "LocaleName": "Chinese (Mandarin, Simplified)",
        "SecondaryLocaleList": [
            "af-ZA",
            "am-ET",
            "ar-EG",
            "ar-SA",
            "az-AZ",
            "bg-BG",
            "bn-BD",
            "bn-IN",
            "bs-BA",
            "ca-ES",
            "cs-CZ",
            "cy-GB",
            "da-DK",
            "de-AT",
            "de-CH",
            "de-DE",
            "el-GR",
            "en-AU",
            "en-CA",
            "en-GB",
            "en-IE",
            "en-IN",
            "en-US",
            "es-ES",
            "es-MX",
            "et-EE",
            "eu-ES",
            "fa-IR",
            "fi-FI",
            "fil-PH",
            "fr-BE",
            "fr-CA",
            "fr-CH",
            "fr-FR",
            "ga-IE",
            "gl-ES",
            "he-IL",
            "hi-IN",
            "hr-HR",
            "hu-HU",
            "hy-AM",
            "id-ID",
            "is-IS",
            "it-IT",
            "ja-JP",
            "jv-ID",
            "ka-GE",
            "kk-KZ",
            "km-KH",
            "kn-IN",
            "ko-KR",
            "lo-LA",
            "lt-LT",
            "lv-LV",
            "mk-MK",
            "ml-IN",
            "mn-MN",
            "ms-MY",
            "mt-MT",
            "my-MM",
            "nb-NO",
            "ne-NP",
            "nl-BE",
            "nl-NL",
            "pl-PL",
            "ps-AF",
            "pt-BR",
            "pt-PT",
            "ro-RO",
            "ru-RU",
            "si-LK",
            "sk-SK",
            "sl-SI",
            "so-SO",
            "sq-AL",
            "sr-RS",
            "su-ID",
            "sv-SE",
            "sw-KE",
            "ta-IN",
            "te-IN",
            "th-TH",
            "tr-TR",
            "uk-UA",
            "ur-PK",
            "uz-UZ",
            "vi-VN",
            "zh-CN",
            "zh-HK",
            "zh-TW",
            "zu-ZA"
        ],
        "SampleRateHertz": "24000",
        "VoiceType": "Neural",
        "Status": "Preview",
        "WordsPerMinute": "190"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN, XiaoxuanNeural)",
        "DisplayName": "Xiaoxuan",
        "LocalName": "晓萱",
        "ShortName": "zh-CN-XiaoxuanNeural",
        "Gender": "Female",
        "Locale": "zh-CN",
        "LocaleName": "Chinese (Mandarin, Simplified)",
        "StyleList": [
            "calm",
            "fearful",
            "cheerful",
            "disgruntled",
            "serious",
            "angry",
            "gentle",
            "depressed"
        ],
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "Deprecated",
        "RolePlayList": [
            "YoungAdultFemale",
            "YoungAdultMale",
            "OlderAdultFemale",
            "OlderAdultMale",
            "SeniorFemale",
            "SeniorMale",
            "Girl",
            "Boy"
        ],
        "WordsPerMinute": "273"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN-guangxi, YunqiNeural)",
        "DisplayName": "Yunqi",
        "LocalName": "云奇",
        "ShortName": "zh-CN-guangxi-YunqiNeural",
        "Gender": "Male",
        "Locale": "zh-CN-guangxi",
        "LocaleName": "Chinese (Guangxi Accent Mandarin, Simplified)",
        "SampleRateHertz": "24000",
        "VoiceType": "Neural",
        "Status": "Preview"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN-henan, YundengNeural)",
        "DisplayName": "Yundeng",
        "LocalName": "云登",
        "ShortName": "zh-CN-henan-YundengNeural",
        "Gender": "Male",
        "Locale": "zh-CN-henan",
        "LocaleName": "Chinese (Zhongyuan Mandarin Henan, Simplified)",
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "WordsPerMinute": "285"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN-liaoning, XiaobeiNeural)",
        "DisplayName": "Xiaobei",
        "LocalName": "晓北",
        "ShortName": "zh-CN-liaoning-XiaobeiNeural",
        "Gender": "Female",
        "Locale": "zh-CN-liaoning",
        "LocaleName": "Chinese (Northeastern Mandarin, Simplified)",
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "Preview",
        "WordsPerMinute": "229"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN-liaoning, YunbiaoNeural)",
        "DisplayName": "Yunbiao",
        "LocalName": "云彪",
        "ShortName": "zh-CN-liaoning-YunbiaoNeural",
        "Gender": "Male",
        "Locale": "zh-CN-liaoning",
        "LocaleName": "Chinese (Northeastern Mandarin, Simplified)",
        "SampleRateHertz": "24000",
        "VoiceType": "Neural",
        "Status": "Preview"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN-shaanxi, XiaoniNeural)",
        "DisplayName": "Xiaoni",
        "LocalName": "晓妮",
        "ShortName": "zh-CN-shaanxi-XiaoniNeural",
        "Gender": "Female",
        "Locale": "zh-CN-shaanxi",
        "LocaleName": "Chinese (Zhongyuan Mandarin Shaanxi, Simplified)",
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "Preview",
        "WordsPerMinute": "263"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN-shandong, YunxiangNeural)",
        "DisplayName": "Yunxiang",
        "LocalName": "云翔",
        "ShortName": "zh-CN-shandong-YunxiangNeural",
        "Gender": "Male",
        "Locale": "zh-CN-shandong",
        "LocaleName": "Chinese (Jilu Mandarin, Simplified)",
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "WordsPerMinute": "279"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-CN-sichuan, YunxiNeural)",
        "DisplayName": "Yunxi",
        "LocalName": "云希",
        "ShortName": "zh-CN-sichuan-YunxiNeural",
        "Gender": "Male",
        "Locale": "zh-CN-sichuan",
        "LocaleName": "Chinese (Southwestern Mandarin, Simplified)",
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "Preview",
        "WordsPerMinute": "285"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-HK, HiuMaanNeural)",
        "DisplayName": "HiuMaan",
        "LocalName": "曉曼",
        "ShortName": "zh-HK-HiuMaanNeural",
        "Gender": "Female",
        "Locale": "zh-HK",
        "LocaleName": "Chinese (Cantonese, Traditional)",
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "WordsPerMinute": "244"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-HK, WanLungNeural)",
        "DisplayName": "WanLung",
        "LocalName": "雲龍",
        "ShortName": "zh-HK-WanLungNeural",
        "Gender": "Male",
        "Locale": "zh-HK",
        "LocaleName": "Chinese (Cantonese, Traditional)",
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "WordsPerMinute": "259"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-HK, HiuGaaiNeural)",
        "DisplayName": "HiuGaai",
        "LocalName": "曉佳",
        "ShortName": "zh-HK-HiuGaaiNeural",
        "Gender": "Female",
        "Locale": "zh-HK",
        "LocaleName": "Chinese (Cantonese, Traditional)",
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "WordsPerMinute": "194"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-TW, HsiaoChenNeural)",
        "DisplayName": "HsiaoChen",
        "LocalName": "曉臻",
        "ShortName": "zh-TW-HsiaoChenNeural",
        "Gender": "Female",
        "Locale": "zh-TW",
        "LocaleName": "Chinese (Taiwanese Mandarin, Traditional)",
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "WordsPerMinute": "272"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-TW, YunJheNeural)",
        "DisplayName": "YunJhe",
        "LocalName": "雲哲",
        "ShortName": "zh-TW-YunJheNeural",
        "Gender": "Male",
        "Locale": "zh-TW",
        "LocaleName": "Chinese (Taiwanese Mandarin, Traditional)",
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "WordsPerMinute": "285"
    },
    {
        "Name": "Microsoft Server Speech Text to Speech Voice (zh-TW, HsiaoYuNeural)",
        "DisplayName": "HsiaoYu",
        "LocalName": "曉雨",
        "ShortName": "zh-TW-HsiaoYuNeural",
        "Gender": "Female",
        "Locale": "zh-TW",
        "LocaleName": "Chinese (Taiwanese Mandarin, Traditional)",
        "SampleRateHertz": "48000",
        "VoiceType": "Neural",
        "Status": "GA",
        "WordsPerMinute": "223"
    }
]


const language = [
    { ShortName: 'wuu-CN', LocalName: '中文（上海话，简体）' },
    { ShortName: 'yue-CN', LocalName: '中文（广东话，简体）' },
    { ShortName: 'zh-CN', LocalName: '中文（普通话，简体）' },
    { ShortName: 'zh-CN-henan', LocalName: '中文（河南话，简体）' },
    { ShortName: 'zh-CN-liaoning', LocalName: '中文（东北话，简体）' },
    { ShortName: 'zh-CN-shaanxi', LocalName: '中文（陕西话，简体）' },
    { ShortName: 'zh-TW', LocalName: '中文（台湾话，繁体）' },
    { ShortName: 'zh-HK', LocalName: '中文（香港话，繁体）' },
    { ShortName: 'zh-CN-sichuan', LocalName: '中文（四川话，简体）' },
    { ShortName: 'zh-CN-shandong', LocalName: '中文（山东话，简体）' }
];

const styles_obj = {
  "advertisement_upbeat": {
    style: "advertisement_upbeat",
    description: "用兴奋和精力充沛的语气推广产品或服务",
  },
  "affectionate": {
    style: "affectionate",
    description:
      "以较高的音调和音量表达温暖而亲切的语气",
  },
  "angry": { style: "angry", description: "表达生气和厌恶的语气" },
  "assistant": {
    style: "assistant",
    description: "数字助理用的是热情而轻松的语气",
  },
  "calm": {
    style: "calm",
    description:
      "以沉着冷静的态度说话",
  },
  "chat": { style: "chat", description: "表达轻松随意的语气" },
  "cheerful": { style: "cheerful", description: "表达积极愉快的语气" },
  "customerservice": {
    style: "customerservice",
    description: "以友好热情的语气为客户提供支持",
  },
  "depressed": {
    style: "depressed",
    description: "调低音调和音量来表达忧郁、沮丧的语气",
  },
  "disgruntled": {
    style: "disgruntled",
    description: "表达轻蔑和抱怨的语气",
  },
  "documentary-narration": {
    style: "documentary-narration",
    description:
      "适合配音纪录片、专家评论和类似内容",
  },
  "embarrassed": {
    style: "embarrassed",
    description: "表达不确定、犹豫的语气",
  },
  "empathetic": { style: "empathetic", description: "表达关心和理解" },
  "envious": {
    style: "envious",
    description: "表达一种钦佩的语气",
  },
  "excited": {
    style: "excited",
    description:
      "表达乐观和充满希望的语气",
  },
  "fearful": {
    style: "fearful",
    description:
      "表达恐惧、紧张的语气",
  },
  "friendly": {
    style: "friendly",
    description: "表达一种愉快、怡人且温暖的语气",
  },
  "gentle": {
    style: "gentle",
    description: "以较低的音调和音量表达温和、礼貌和愉快的语气",
  },
  "hopeful": {
    style: "hopeful",
    description:
      "表达一种温暖且渴望的语气",
  },
  "lyrical": { style: "lyrical", description: "以优美又带感伤的方式表达情感" },
  "narration-professional": {
    style: "narration-professional",
    description: "以专业、客观的语气朗读内容",
  },
  "narration-relaxed": {
    style: "narration-relaxed",
    description: "为内容阅读表达一种舒缓而悦耳的语气",
  },
  newscast: { style: "newscast", description: "以正式专业的语气叙述新闻" },
  "newscast-casual": {
    style: "newscast-casual",
    description: "以通用、随意的语气发布一般新闻",
  },
  "newscast-formal": {
    style: "newscast-formal",
    description: "以正式、自信和权威的语气发布新闻",
  },
  "poetry-reading": {
    style: "poetry-reading",
    description: "在读诗时表达出带情感和节奏的语气",
  },
  "sad": { style: "sad", description: "表达悲伤语气" },
  "serious": {
    style: "serious",
    description:
      "表达严肃和命令的语气",
  },
  "shouting": {
    style: "shouting",
    description:
      "听起来好像声音在远处或在另一个地方的语气",
  },
  
  "sports-commentary": {
    style: "sports-commentary",
    description: "轻松又感兴趣的语气，用于播报体育赛事",
  },
  "sports-commentary-excited": {
    style: "sports-commentary-excited",
    description: "用快速且充满活力的语气播报体育赛事精彩瞬间",
  },
  "whispering": {
    style: "whispering",
    description: "表达一种柔和的语气，试图发出安静而柔和的声音",
  },
  "terrified": {
    style: "terrified",
    description:
      "表达一种害怕的语气，语速快且声音颤抖",
  },
  "unfriendly": { style: "unfriendly", description: "表达一种冷淡无情的语气。" },
};

const roles_obj = [
    { role: "Girl", description: "女孩" },
    { role: "Boy", description: "男孩" },
    { role: "YoungAdultFemale", description: "年轻的成年女性" },
    { role: "YoungAdultMale", description: "年轻的成年男性" },
    { role: "OlderAdultFemale", description: "年长的成年女性" },
    { role: "OlderAdultMale", description: "年长的成年男性" },
    { role: "SeniorFemale", description: "年老女性" },
    { role: "SeniorMale", description: "年老男性" }
]


const quality = [
    {'option':"16Khz32KBit",'value':'Audio16Khz32KBitRateMonoMp3'},
    {'option':"24Khz160KBit",'value':'Audio24Khz160KBitRateMonoMp3'},
    {'option':"48Khz192KBit",'value':'Audio48Khz192KBitRateMonoMp3'},
    {'option':"16Khz16BitMonoPcm",'value':'Raw16Khz16BitMonoPcm'}
]

const rate=[
    {'option':'⏪ 0.5x',value:'0.5'},
    {'option':'⏪ 0.6x',value:'0.6'},
    {'option':'⏪ 0.7x',value:'0.7'},
    {'option':'⏪ 0.8x',value:'0.8'},
    {'option':'⏪ 0.85x',value:'0.85'},
    {'option':'⏪ 0.9x',value:'0.9'},
    {'option':'⏪ 0.95x',value:'0.95'},
    {'option':'1x(默认)',value:'1'},
    {'option':'⏩ 1.05x',value:'1.05'},
    {'option':'⏩ 1.1x',value:'1.1'},
    {'option':'⏩ 1.15x',value:'1.15'},
    {'option':'⏩ 1.2x',value:'1.2'},
    {'option':'⏩ 1.25x',value:'1.25'},
    {'option':'⏩ 1.3x',value:'1.3'},
    {'option':'⏩ 1.4x',value:'1.4'},
    {'option':'⏩ 1.5x',value:'1.5'},
    {'option':'⏩ 2x',value:'2'}
]

const volume = [
    {'option':'🔽 10%',value: 0.1 },
    {'option':'🔽 30%',value: 0.3 },
    {'option':'🔽 50%',value: 0.5 },
    {'option':'🔽 80%',value: 0.8 },
    {'option':'100%',value: 1 },
    {'option':'🔼 120%',value: 1.2 },
    {'option':'🔼 150%',value: 1.5 },
    {'option':'🔼 180%',value: 1.8 },
    {'option':'🔼 200%',value: 2 },
]

const pitch = [
    {'option':'🔼 Super High pitch (+100%)',value:2},
    {'option':'🔼 Super High pitch (+50%)',value:1.5},
    {'option':'🔼 Super High pitch (+25)',value:1.25},
    {'option':'🔼 Super High pitch (+10%)',value:1.1},
    {'option':'🔼 Super High pitch (+5%)',value:1.05},
    {'option':'Default (normal pitch)',value:1},
    {'option':'🔽 Slightly low pitch (-5%)',value:0.95},
    {'option':'🔽 Slightly low pitch (-10%)',value:0.9},
    {'option':'🔽 Slightly low pitch (-25%)',value:0.75},
    {'option':'🔽 Slightly low pitch (-50%)',value:0.5}
]
const silence = [
    {'option':'0ms',value:'0'},
    {'option':'50ms',value:'50'},
    {'option':'100ms',value:'100'},
    {'option':'200ms',value:'200'},
    {'option':'300ms',value:'300'},
    {'option':'600ms',value:'600'},
    {'option':'800ms',value:'380'},
    {'option':'1000ms',value:'1000'},
    {'option':'1200ms',value:'1200'},
    {'option':'1500ms',value:'1500'},
    {'option':'2000ms',value:'2000'},
    {'option':'3000ms',value:'3000'},
    {'option':'4000ms',value:'4000'},
    {'option':'5000ms',value:'5000'}
]

const pause = [
    {'option':'0.4s',value:'400ms'},
    {'option':'0.5s',value:'500ms'},
    {'option':'0.8s',value:'500ms'},
    {'option':'1s',value:'1000ms'},
    {'option':'1.5s',value:'1500ms'},
    {'option':'2s',value:'2000ms'},
    {'option':'3s',value:'3000ms'},
    {'option':'5s',value:'5000ms'}
]
const fileterVoices = (voice)=>voices.filter(sp=>sp.Locale==voice)


const filteredStyles = (styles)=>styles.map(style => {
    return styles_obj[style]
}).filter(style => style !== undefined);


const filteredRoles = (roles)=>{
   return roles_obj.filter(roleObj => roles.includes(roleObj.role));
}

export  {
    language,
    quality,
    styles_obj,
    volume,
    rate,
    pitch,
    silence,
    pause,
    fileterVoices,
    filteredStyles,
    filteredRoles
}